mod cli;

use clap::Parser;
use cli::{Cli, EngineArg};
use markitdown_core::{
    ConvertOptions, ConvertResult, Engine, MarkItDown, StreamInfo, SUPPORTED_FORMATS,
};
use rayon::prelude::*;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

/// Man page generated by build.rs (clap_mangen), embedded so the binary
/// stays a single self-contained file.
const MAN_PAGE: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/markitdown.1"));

fn main() -> ExitCode {
    let args = Cli::parse();

    if args.version {
        return print_or_pipe_ok(format!("markitdown {}\n", env!("CARGO_PKG_VERSION")).as_bytes());
    }
    if args.emit_man {
        return print_or_pipe_ok(MAN_PAGE);
    }
    if args.list_formats {
        let mut buf = String::new();
        for f in SUPPORTED_FORMATS {
            buf.push_str(&format!(
                "{:<24} {:<44} {}\n",
                f.name,
                f.extensions.join(" "),
                f.notes
            ));
        }
        return print_or_pipe_ok(buf.as_bytes());
    }

    let opts = ConvertOptions {
        keep_data_uris: args.keep_data_uris,
        engine: match args.engine {
            EngineArg::Rust => Engine::Rust,
            EngineArg::Python => Engine::Python,
            EngineArg::Auto => Engine::Auto,
        },
        python_bin: args.python_bin.clone(),
        // LLM captions are env-driven (MARKITDOWN_LLM_API_KEY/MODEL).
        llm: None,
    };
    let md = MarkItDown::with_options(opts);

    match args.inputs.len() {
        0 => convert_stdin(&md, &args),
        1 if args.output_dir.is_none() => {
            convert_single(&md, &args.inputs[0], args.output.as_deref())
        }
        _ => convert_batch(&md, &args),
    }
}

/// Convert stdin with optional -x/-m/-c hints.
fn convert_stdin(md: &MarkItDown, args: &Cli) -> ExitCode {
    let mut data = Vec::new();
    if let Err(e) = std::io::stdin().read_to_end(&mut data) {
        eprintln!("error: reading stdin: {e}");
        return ExitCode::FAILURE;
    }
    let mut hints = StreamInfo::new();
    if let Some(x) = &args.extension {
        hints = hints.with_extension(x);
    }
    if let Some(m) = &args.mime_type {
        hints = hints.with_mimetype(m);
    }
    if let Some(c) = &args.charset {
        hints = hints.with_charset(c);
    }
    match md.convert_bytes(&data, hints) {
        Ok(result) => emit(&result, args.output.as_deref()),
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

fn convert_single(md: &MarkItDown, input: &str, output: Option<&Path>) -> ExitCode {
    match md.convert_uri(input) {
        Ok(result) => emit(&result, output),
        Err(e) => {
            eprintln!("error: {input}: {e}");
            ExitCode::FAILURE
        }
    }
}

/// Parallel batch conversion (the "many heavy jobs" path): every input is
/// converted on the rayon thread pool and written to --output-dir.
fn convert_batch(md: &MarkItDown, args: &Cli) -> ExitCode {
    let Some(out_dir) = &args.output_dir else {
        eprintln!("error: multiple inputs require -O/--output-dir");
        return ExitCode::FAILURE;
    };
    if let Err(e) = std::fs::create_dir_all(out_dir) {
        eprintln!("error: creating {}: {e}", out_dir.display());
        return ExitCode::FAILURE;
    }

    let names = output_names(&args.inputs);
    let failures: usize = args
        .inputs
        .par_iter()
        .zip(names.par_iter())
        .map(|(input, name)| {
            let dest = out_dir.join(name);
            let outcome = md
                .convert_uri(input)
                .and_then(|r| Ok(std::fs::write(&dest, r.markdown.as_bytes())?));
            match outcome {
                Ok(()) => {
                    eprintln!("ok: {input} -> {}", dest.display());
                    0
                }
                Err(e) => {
                    eprintln!("FAILED: {input}: {e}");
                    1
                }
            }
        })
        .sum();

    if failures > 0 {
        eprintln!("{failures}/{} conversions failed", args.inputs.len());
        ExitCode::FAILURE
    } else {
        ExitCode::SUCCESS
    }
}

/// The final file-name component of an input.
///
/// Must be platform-aware: a batch input is either a URI (`https://…/x.html`)
/// or a local filesystem path, and on Windows local paths use `\` separators.
/// Splitting only on `/` left a full `C:\dir\file.docx` intact, which then
/// escaped the output directory when joined (an absolute path replaces the
/// base) — the Windows batch failure. URIs keep the `/`-split + query strip.
fn last_segment(input: &str) -> String {
    if input.contains("://") {
        // URI-like: strip query/fragment from the last `/` segment.
        return input
            .trim_end_matches('/')
            .rsplit('/')
            .next()
            .unwrap_or(input)
            .split(['?', '#'])
            .next()
            .unwrap_or(input)
            .to_string();
    }
    // Local path: let std handle the platform's separators.
    Path::new(input)
        .file_name()
        .map(|s| s.to_string_lossy().into_owned())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| input.to_string())
}

/// Output names for a batch; when two inputs share a stem (test.docx and
/// test.xlsx), the original extension is kept: test.docx.md / test.xlsx.md.
fn output_names(inputs: &[String]) -> Vec<PathBuf> {
    let plain: Vec<PathBuf> = inputs.iter().map(|i| output_name(i)).collect();
    inputs
        .iter()
        .zip(&plain)
        .map(|(input, name)| {
            if plain.iter().filter(|n| *n == name).count() > 1 {
                PathBuf::from(format!("{}.md", last_segment(input)))
            } else {
                name.clone()
            }
        })
        .collect()
}

/// `dir/report.pdf` → `report.md`; URIs use their last path segment.
fn output_name(input: &str) -> PathBuf {
    let last = last_segment(input);
    let stem = Path::new(&last)
        .file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "output".to_string());
    PathBuf::from(format!("{stem}.md"))
}

fn emit(result: &ConvertResult, output: Option<&Path>) -> ExitCode {
    match output {
        Some(path) => {
            if let Err(e) = std::fs::write(path, result.markdown.as_bytes()) {
                eprintln!("error: writing {}: {e}", path.display());
                return ExitCode::FAILURE;
            }
            ExitCode::SUCCESS
        }
        None => {
            let mut bytes = result.markdown.clone().into_bytes();
            if !result.markdown.ends_with('\n') {
                bytes.push(b'\n');
            }
            print_or_pipe_ok(&bytes)
        }
    }
}

/// Write `bytes` to stdout, treating a closed downstream pipe as a clean exit.
///
/// A normal Unix CLI piped into `head`/`grep -q` should not crash when the
/// reader closes early; Rust otherwise turns the resulting `BrokenPipe` write
/// error into a panic ("failed printing to stdout"). We map BrokenPipe to a
/// success exit (the consumer already got what it wanted) and surface any
/// other I/O error as a failure. Cross-platform: Windows reports the same
/// `ErrorKind::BrokenPipe` when the pipe peer goes away.
fn print_or_pipe_ok(bytes: &[u8]) -> ExitCode {
    let mut stdout = std::io::stdout().lock();
    match stdout.write_all(bytes).and_then(|_| stdout.flush()) {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) if e.kind() == std::io::ErrorKind::BrokenPipe => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: writing to stdout: {e}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{output_name, output_names};
    use std::path::{Path, PathBuf};

    #[test]
    fn output_name_basic() {
        assert_eq!(output_name("dir/report.pdf"), PathBuf::from("report.md"));
        assert_eq!(
            output_name("https://x.io/a/page.html?q=1"),
            PathBuf::from("page.md")
        );
        assert_eq!(output_name(".hidden"), PathBuf::from(".hidden.md"));
    }

    #[test]
    fn duplicate_stems_keep_extension() {
        // The case the Windows batch test exercises (test.docx + test.xlsx).
        let inputs = vec![
            "a/test.docx".to_string(),
            "b/test.xlsx".to_string(),
            "c/blog.html".to_string(),
        ];
        assert_eq!(
            output_names(&inputs),
            vec![
                PathBuf::from("test.docx.md"),
                PathBuf::from("test.xlsx.md"),
                PathBuf::from("blog.md"),
            ]
        );
    }

    /// Core invariant (runs on every platform, incl. macOS & Linux):
    /// a batch output name is ALWAYS a single relative component — never a
    /// path that could escape the `--output-dir` when joined. This is exactly
    /// what broke on Windows, where an un-split `C:\dir\test.docx` produced an
    /// absolute name that replaced the output directory.
    #[test]
    fn output_names_never_escape_output_dir() {
        // Forward-slash paths + URIs are valid on every platform (Windows
        // accepts `/` too). Backslash paths are exercised by the
        // windows-only test, since `\` is not a separator on Unix.
        let inputs = vec![
            "/abs/unix/test.docx".to_string(),
            "/abs/unix/test.xlsx".to_string(), // duplicate stem -> collision branch
            "relative/report.pdf".to_string(),
            "https://example.com/a/b/page.html?x=1#frag".to_string(),
        ];
        for name in output_names(&inputs) {
            assert!(name.is_relative(), "{name:?} must be relative");
            assert_eq!(
                Path::new(&name).components().count(),
                1,
                "{name:?} must be a single path component (no separators)"
            );
            let s = name.to_string_lossy();
            assert!(!s.contains('/') && !s.contains('\\'), "{s} contains a separator");
            assert!(s.ends_with(".md"));
        }
    }

    // Windows-only: backslash is a real separator there, so the last segment
    // is the bare file name. (On Unix `\` is an ordinary character, so these
    // exact equalities only hold on Windows.)
    #[cfg(windows)]
    #[test]
    fn windows_backslash_paths() {
        assert_eq!(output_name(r"C:\tmp\test.docx"), PathBuf::from("test.md"));
        assert_eq!(
            output_names(&[r"C:\tmp\test.docx".to_string(), r"D:\x\test.xlsx".to_string()]),
            vec![PathBuf::from("test.docx.md"), PathBuf::from("test.xlsx.md")]
        );
    }
}
