# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from markitdown.grpc.v1 import markitdown_pb2 as markitdown_dot_v1_dot_markitdown__pb2

GRPC_GENERATED_VERSION = "1.81.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in markitdown/v1/markitdown_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MarkItDownServiceStub:
    """MarkItDownService converts documents (PDF, Office, HTML, images, audio,
    and more) to Markdown suitable for LLM and text-analysis pipelines.

    Security note: the server performs I/O with the privileges of the server
    process. `Source.local_path` and `Source.uri` are resolved server-side, so
    requests must come from trusted callers only. See the project README's
    "Security Considerations" section.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Convert = channel.unary_unary(
            "/markitdown.v1.MarkItDownService/Convert",
            request_serializer=markitdown_dot_v1_dot_markitdown__pb2.ConvertRequest.SerializeToString,
            response_deserializer=markitdown_dot_v1_dot_markitdown__pb2.ConvertResponse.FromString,
            _registered_method=True,
        )
        self.ConvertStream = channel.unary_stream(
            "/markitdown.v1.MarkItDownService/ConvertStream",
            request_serializer=markitdown_dot_v1_dot_markitdown__pb2.ConvertStreamRequest.SerializeToString,
            response_deserializer=markitdown_dot_v1_dot_markitdown__pb2.ConvertStreamResponse.FromString,
            _registered_method=True,
        )
        self.ConvertDocumentStream = channel.unary_stream(
            "/markitdown.v1.MarkItDownService/ConvertDocumentStream",
            request_serializer=markitdown_dot_v1_dot_markitdown__pb2.ConvertDocumentStreamRequest.SerializeToString,
            response_deserializer=markitdown_dot_v1_dot_markitdown__pb2.ConvertDocumentStreamResponse.FromString,
            _registered_method=True,
        )


class MarkItDownServiceServicer:
    """MarkItDownService converts documents (PDF, Office, HTML, images, audio,
    and more) to Markdown suitable for LLM and text-analysis pipelines.

    Security note: the server performs I/O with the privileges of the server
    process. `Source.local_path` and `Source.uri` are resolved server-side, so
    requests must come from trusted callers only. See the project README's
    "Security Considerations" section.
    """

    def Convert(self, request, context):
        """Convert performs a conversion and returns the complete Markdown
        result in a single response message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ConvertStream(self, request, context):
        """ConvertStream performs a conversion and delivers the Markdown result
        as an ordered stream of chunks. The conversion itself completes before
        chunking begins; streaming reduces time-to-first-byte on the wire and
        keeps individual messages small, but does not stream partial conversion
        progress.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ConvertDocumentStream(self, request, context):
        """ConvertDocumentStream performs a conversion and delivers the result as
        an ordered stream of structured document elements (headings, paragraphs,
        tables, lists, code blocks, images, ...). This lets downstream consumers
        process document structure incrementally without re-parsing Markdown.

        Segmentation is performed on the converted Markdown and is best-effort:
        constructs that do not match a known block type are delivered as
        paragraphs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MarkItDownServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Convert": grpc.unary_unary_rpc_method_handler(
            servicer.Convert,
            request_deserializer=markitdown_dot_v1_dot_markitdown__pb2.ConvertRequest.FromString,
            response_serializer=markitdown_dot_v1_dot_markitdown__pb2.ConvertResponse.SerializeToString,
        ),
        "ConvertStream": grpc.unary_stream_rpc_method_handler(
            servicer.ConvertStream,
            request_deserializer=markitdown_dot_v1_dot_markitdown__pb2.ConvertStreamRequest.FromString,
            response_serializer=markitdown_dot_v1_dot_markitdown__pb2.ConvertStreamResponse.SerializeToString,
        ),
        "ConvertDocumentStream": grpc.unary_stream_rpc_method_handler(
            servicer.ConvertDocumentStream,
            request_deserializer=markitdown_dot_v1_dot_markitdown__pb2.ConvertDocumentStreamRequest.FromString,
            response_serializer=markitdown_dot_v1_dot_markitdown__pb2.ConvertDocumentStreamResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "markitdown.v1.MarkItDownService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "markitdown.v1.MarkItDownService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class MarkItDownService:
    """MarkItDownService converts documents (PDF, Office, HTML, images, audio,
    and more) to Markdown suitable for LLM and text-analysis pipelines.

    Security note: the server performs I/O with the privileges of the server
    process. `Source.local_path` and `Source.uri` are resolved server-side, so
    requests must come from trusted callers only. See the project README's
    "Security Considerations" section.
    """

    @staticmethod
    def Convert(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/markitdown.v1.MarkItDownService/Convert",
            markitdown_dot_v1_dot_markitdown__pb2.ConvertRequest.SerializeToString,
            markitdown_dot_v1_dot_markitdown__pb2.ConvertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ConvertStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/markitdown.v1.MarkItDownService/ConvertStream",
            markitdown_dot_v1_dot_markitdown__pb2.ConvertStreamRequest.SerializeToString,
            markitdown_dot_v1_dot_markitdown__pb2.ConvertStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ConvertDocumentStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/markitdown.v1.MarkItDownService/ConvertDocumentStream",
            markitdown_dot_v1_dot_markitdown__pb2.ConvertDocumentStreamRequest.SerializeToString,
            markitdown_dot_v1_dot_markitdown__pb2.ConvertDocumentStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
