"""
Reproducer for microsoft/markitdown issue #1845:
Academic PDF conversion outputs non-standard Markdown with broken formatting.

Root cause: pdfminer.six extracts text in PDF storage order, not visual reading
order. Two-column journal layouts get interleaved mid-sentence between columns,
and table cells come out scrambled.
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from markitdown import MarkItDown


PDF_PATH = "two_column_academic.pdf"

LEFT_COL_TEXT = [
    "Abstract",
    "",
    "This study investigates the removal of pharmaceutical",
    "contaminants (sartans) using iron-cycling constructed",
    "wetland microbial fuel cells (CW-MFC). Results show",
    "a 94.3% removal efficiency under optimized conditions.",
    "The anodic iron oxidation drives electron transfer,",
    "enhancing microbial degradation pathways.",
    "",
    "1. Introduction",
    "",
    "Emerging contaminants such as angiotensin receptor",
    "blockers (ARBs) pose significant risks to aquatic",
    "ecosystems. Conventional wastewater treatment plants",
    "fail to fully remove these compounds. Constructed",
    "wetlands coupled with microbial fuel cells represent",
    "a promising low-energy alternative.",
    "",
    "2. Materials and Methods",
    "",
    "CW-MFC reactors (30 L) were packed with iron filings",
    "and gravel media. Synthetic wastewater spiked with",
    "valsartan (10 mg/L) was fed at HRT = 3 days.",
]

RIGHT_COL_TEXT = [
    "3. Results",
    "",
    "Table 1 summarizes contaminant removal across",
    "experimental runs. At Fe(II) concentration of 5 mM,",
    "sartan removal reached 94.3 +/- 1.2%. Voltage output",
    "stabilized at 320 mV after 14 days of operation.",
    "",
    "4. Discussion",
    "",
    "The enhanced removal is attributed to Fenton-like",
    "reactions generated by Fe(II)/Fe(III) cycling. The",
    "MFC component accelerates iron oxidation at the anode,",
    "sustaining reactive oxygen species production.",
    "Microbial community analysis revealed enrichment of",
    "Geobacter and Desulfovibrio species.",
    "",
    "5. Conclusion",
    "",
    "Iron-cycling CW-MFC systems achieve high sartan",
    "removal with concurrent electricity generation.",
    "This technology offers a sustainable approach to",
    "pharmaceutical wastewater treatment.",
]


def create_two_column_pdf(path):
    c = canvas.Canvas(path, pagesize=letter)
    width, height = letter

    # Title
    c.setFont("Helvetica-Bold", 14)
    c.drawCentredString(width / 2, height - 0.75 * inch,
        "Iron-Cycling CW-MFC Enhanced Removal of Sartans")
    c.setFont("Helvetica", 10)
    c.drawCentredString(width / 2, height - 1.05 * inch,
        "Zhang et al. | Environmental Science & Technology | 2026")

    # Divider line
    c.setStrokeColor(colors.black)
    c.line(inch, height - 1.2 * inch, width - inch, height - 1.2 * inch)

    # Column layout
    col_width = (width - 2.5 * inch) / 2
    left_x = inch
    right_x = inch + col_width + 0.5 * inch
    top_y = height - 1.5 * inch
    line_height = 13

    def draw_column(x, lines, start_y):
        c.setFont("Helvetica", 9)
        y = start_y
        for line in lines:
            if line and line[0].isdigit() and "." in line[:3]:
                c.setFont("Helvetica-Bold", 9)
                c.drawString(x, y, line)
                c.setFont("Helvetica", 9)
            elif line in ("Abstract",):
                c.setFont("Helvetica-Bold", 9)
                c.drawString(x, y, line)
                c.setFont("Helvetica", 9)
            else:
                # Wrap text within column width
                words = line.split()
                current = ""
                for word in words:
                    test = (current + " " + word).strip()
                    if c.stringWidth(test, "Helvetica", 9) < col_width - 10:
                        current = test
                    else:
                        c.drawString(x, y, current)
                        y -= line_height
                        current = word
                if current:
                    c.drawString(x, y, current)
            y -= line_height
        return y

    draw_column(left_x, LEFT_COL_TEXT, top_y)
    draw_column(right_x, RIGHT_COL_TEXT, top_y)

    # Column separator
    mid_x = inch + col_width + 0.25 * inch
    c.setDash(3, 3)
    c.line(mid_x, height - 1.25 * inch, mid_x, 1.5 * inch)

    c.save()
    print(f"Created: {path}")


def run_markitdown(path):
    md = MarkItDown()
    result = md.convert(path)
    return result.text_content


def main():
    print("=== Reproducer for issue #1845 ===\n")

    create_two_column_pdf(PDF_PATH)

    print("Running markitdown on two-column academic PDF...\n")
    output = run_markitdown(PDF_PATH)

    print("--- markitdown output ---")
    print(output)
    print("--- end of output ---\n")

    # Diagnose the interleaving problem
    lines = [l for l in output.splitlines() if l.strip()]
    left_markers = ["Abstract", "Introduction", "Materials", "Methods"]
    right_markers = ["Results", "Discussion", "Conclusion"]

    print("=== Issue diagnosis ===")
    print("Expected: left column content followed by right column content.")
    print("Actual order of section headers found:\n")
    for i, line in enumerate(lines):
        for m in left_markers + right_markers:
            if m in line:
                side = "LEFT col" if m in left_markers else "RIGHT col"
                print(f"  line {i:3d}: [{side}] {line.strip()}")

    print("\nIf LEFT and RIGHT column sections interleave, the bug is reproduced.")


if __name__ == "__main__":
    main()
