//! markitdown-mcp — MCP server (stdio transport) exposing MarkItDown
//! file-to-Markdown conversion to Claude and other MCP clients.
//!
//! Design notes (token-efficiency first):
//! - Small, focused tool surface: 4 tools.
//! - `convert_to_markdown` pages output (`max_chars`/`offset`) so a large PDF
//!   can never flood the client's context window.
//! - `convert_file` can write to disk and return only a summary + preview.
//! - All logging goes to stderr: stdout belongs exclusively to the protocol.

use rmcp::{
    handler::server::wrapper::Parameters,
    model::{CallToolResult, Content, Implementation, ServerCapabilities, ServerInfo},
    schemars, tool, tool_handler, tool_router,
    transport::stdio,
    ErrorData as McpError, ServerHandler, ServiceExt,
};

/// Default page size for inline conversion results (~12k tokens).
const DEFAULT_MAX_CHARS: usize = 50_000;

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ConvertRequest {
    #[schemars(
        description = "Source to convert: absolute file path, or file:/data:/http(s): URI"
    )]
    pub uri: String,
    #[schemars(
        description = "Max characters to return (default 50000). Longer output is paged; a trailing note gives the offset to resume from."
    )]
    pub max_chars: Option<usize>,
    #[schemars(description = "Character offset to resume a paged result from (default 0)")]
    pub offset: Option<usize>,
    #[schemars(
        description = "Engine override: 'auto' (default; Rust with Python fallback for OCR & co.), 'rust' (pure Rust), or 'python' (force full Python fidelity, e.g. PDF table reconstruction; needs MARKITDOWN_PY_BIN)"
    )]
    pub engine: Option<String>,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ConvertFileRequest {
    #[schemars(description = "Absolute path of the file to convert")]
    pub path: String,
    #[schemars(
        description = "When set, the Markdown is written to this path and only a short summary + preview is returned (recommended for large documents)"
    )]
    pub output_path: Option<String>,
    #[schemars(description = "Engine override: 'auto' (default) | 'rust' | 'python'")]
    pub engine: Option<String>,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ConvertBatchRequest {
    #[schemars(description = "Absolute paths of files to convert (processed in parallel)")]
    pub paths: Vec<String>,
    #[schemars(description = "Directory to write the .md outputs into (created if missing)")]
    pub output_dir: String,
    #[schemars(description = "Engine override: 'auto' (default) | 'rust' | 'python'")]
    pub engine: Option<String>,
}

/// Stateless server: `#[tool_handler]` resolves the router via the
/// `Self::tool_router()` generated by `#[tool_router]`, so no fields needed.
#[derive(Clone, Default)]
pub struct MarkitdownServer;

fn engine(choice: Option<&str>) -> markitdown_core::MarkItDown {
    // Default Auto: pure Rust, with transparent fallback to the optional
    // Python binary (MARKITDOWN_PY_BIN) for cases Rust can't handle (OCR,
    // transcription, DOCX comments/equations, RTF email bodies, …).
    let engine = match choice {
        Some("rust") => markitdown_core::Engine::Rust,
        Some("python") => markitdown_core::Engine::Python,
        _ => markitdown_core::Engine::Auto,
    };
    markitdown_core::MarkItDown::with_options(markitdown_core::ConvertOptions {
        engine,
        ..Default::default()
    })
}

fn ok_text(s: impl Into<String>) -> CallToolResult {
    CallToolResult::success(vec![Content::text(s)])
}

fn internal(e: impl std::fmt::Display) -> McpError {
    McpError::internal_error(e.to_string(), None)
}

#[tool_router]
impl MarkitdownServer {
    pub fn new() -> Self {
        Self
    }

    #[tool(
        description = "Convert a document (PDF, DOCX, XLSX, PPTX, HTML, CSV, EPUB, ZIP, ipynb, .msg, RSS, images, audio, text) to Markdown and return it. Accepts a file path or file:/data:/http(s): URI. Large results are paged via max_chars/offset."
    )]
    async fn convert_to_markdown(
        &self,
        Parameters(req): Parameters<ConvertRequest>,
    ) -> Result<CallToolResult, McpError> {
        let uri = req.uri.clone();
        let choice = req.engine.clone();
        let result =
            tokio::task::spawn_blocking(move || engine(choice.as_deref()).convert_uri(&uri))
                .await
                .map_err(internal)?
                .map_err(internal)?;

        let md = result.markdown;
        let total = md.chars().count();
        let offset = req.offset.unwrap_or(0);
        let max_chars = req.max_chars.unwrap_or(DEFAULT_MAX_CHARS).max(1);

        if offset >= total && total > 0 {
            return Err(McpError::invalid_params(
                format!("offset {offset} is past the end of the {total}-char document"),
                None,
            ));
        }
        let page: String = md.chars().skip(offset).take(max_chars).collect();
        let end = offset + page.chars().count();
        let mut out = page;
        if end < total {
            out.push_str(&format!(
                "\n\n[truncated: chars {offset}..{end} of {total}; call convert_to_markdown again with offset={end} for the next page]"
            ));
        }
        Ok(ok_text(out))
    }

    #[tool(
        description = "Convert a local file to Markdown. With output_path set, writes the result to disk and returns only title/char-count/output path plus a 500-char preview — use this for large documents to keep context small, then read specific sections from the written file."
    )]
    async fn convert_file(
        &self,
        Parameters(req): Parameters<ConvertFileRequest>,
    ) -> Result<CallToolResult, McpError> {
        let path = req.path.clone();
        let choice = req.engine.clone();
        let result =
            tokio::task::spawn_blocking(move || engine(choice.as_deref()).convert_path(&path))
                .await
                .map_err(internal)?
                .map_err(internal)?;

        match &req.output_path {
            Some(dest) => {
                std::fs::write(dest, result.markdown.as_bytes()).map_err(internal)?;
                let preview: String = result.markdown.chars().take(500).collect();
                Ok(ok_text(format!(
                    "written: {dest}\ntitle: {}\nchars: {}\npreview:\n{preview}",
                    result.title.as_deref().unwrap_or("(none)"),
                    result.markdown.chars().count(),
                )))
            }
            None => Ok(ok_text(result.markdown)),
        }
    }

    #[tool(
        description = "Convert many local files to Markdown in parallel, writing one .md per input into output_dir. Returns one status line per file. Use this for bulk jobs instead of repeated convert_file calls."
    )]
    async fn convert_batch(
        &self,
        Parameters(req): Parameters<ConvertBatchRequest>,
    ) -> Result<CallToolResult, McpError> {
        let report = tokio::task::spawn_blocking(move || {
            use rayon::prelude::*;
            std::fs::create_dir_all(&req.output_dir)?;
            let lines: Vec<String> = req
                .paths
                .par_iter()
                .map(|p| {
                    let name = std::path::Path::new(p)
                        .file_name()
                        .map(|n| n.to_string_lossy().into_owned())
                        .unwrap_or_else(|| "output".into());
                    let dest = std::path::Path::new(&req.output_dir).join(format!("{name}.md"));
                    match engine(req.engine.as_deref())
                        .convert_path(p)
                        .and_then(|r| Ok(std::fs::write(&dest, r.markdown.as_bytes())?))
                    {
                        Ok(()) => format!("ok: {p} -> {}", dest.display()),
                        Err(e) => format!("FAILED: {p}: {e}"),
                    }
                })
                .collect();
            Ok::<_, std::io::Error>(lines.join("\n"))
        })
        .await
        .map_err(internal)?
        .map_err(internal)?;
        Ok(ok_text(report))
    }

    #[tool(
        description = "List the file formats this server can convert, with extensions and caveats, plus whether the Python fallback engine (OCR/transcription) and LLM image captions are currently available. Cheap; call once if unsure."
    )]
    async fn list_supported_formats(&self) -> Result<CallToolResult, McpError> {
        let mut out = String::from("format | extensions | notes\n");
        for f in markitdown_core::SUPPORTED_FORMATS {
            out.push_str(&format!(
                "{} | {} | {}\n",
                f.name,
                f.extensions.join(" "),
                f.notes
            ));
        }
        // Capabilities reflect the server's environment (MARKITDOWN_PY_BIN,
        // MARKITDOWN_LLM_*). No secrets are included.
        let caps = markitdown_core::capabilities(&markitdown_core::ConvertOptions::default());
        out.push_str(&format!(
            "\npython fallback engine (OCR, transcription, RTF bodies, transcripts): {}\n",
            if caps.python_engine {
                "AVAILABLE — degraded conversions retry automatically"
            } else {
                "not configured (set MARKITDOWN_PY_BIN)"
            }
        ));
        out.push_str(&format!(
            "llm image captions: {}\n",
            if caps.llm_captions {
                format!(
                    "AVAILABLE — images get a '# Description:' section (model={}, endpoint={})",
                    caps.llm_model.as_deref().unwrap_or("?"),
                    caps.llm_api_base.as_deref().unwrap_or("?")
                )
            } else {
                "not configured (set MARKITDOWN_LLM_API_KEY + MARKITDOWN_LLM_MODEL; \
                 MARKITDOWN_LLM_API_BASE for local LLMs)"
                    .to_string()
            }
        ));
        Ok(ok_text(out))
    }
}

#[tool_handler]
impl ServerHandler for MarkitdownServer {
    fn get_info(&self) -> ServerInfo {
        // Implementation is #[non_exhaustive]; mutate a default instead.
        let mut server_info = Implementation::default();
        server_info.name = env!("CARGO_PKG_NAME").to_string();
        server_info.version = env!("CARGO_PKG_VERSION").to_string();
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(server_info)
            .with_instructions(
                "Converts documents (PDF, Office, HTML, EPUB, ZIP, images, audio, …) to \
                 Markdown. For large files prefer convert_file with output_path (returns a \
                 summary, not the whole text). convert_to_markdown pages with max_chars/offset. \
                 Use convert_batch for many files.",
            )
    }
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    // stdio transport: stdout is the protocol channel — log to stderr only.
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "info".into()),
        )
        .with_writer(std::io::stderr)
        .with_ansi(false)
        .init();

    tracing::info!(
        "markitdown-mcp {} starting (stdio transport)",
        env!("CARGO_PKG_VERSION")
    );
    let service = MarkitdownServer::new().serve(stdio()).await?;
    service.waiting().await?;
    Ok(())
}
